"""Tests for src.parser against the synthetic fixtures (phases.md Phase 2 DoD).

These exercise real Docling conversion rather than mocks. Docling is the component whose
behaviour we are least able to assume, so mocking it here would test nothing that matters.
The converter is cached at module scope, so the ~20 s model load is paid once per session.

No LLM is called anywhere in this module — parsing is entirely local (decision D-15).
"""

from __future__ import annotations

import time

import pytest

from src import ParsingError
from src.config import FIXTURES_DIR, get_settings
from src.parser import parse_document
from src.schemas import ParsedDocument

pytestmark = pytest.mark.slow

CLEAN = FIXTURES_DIR / "clean_invoice.pdf"
UNBALANCED = FIXTURES_DIR / "unbalanced_invoice.pdf"
MULTIPAGE = FIXTURES_DIR / "multipage_statement.pdf"
SCANNED = FIXTURES_DIR / "scanned_receipt.png"
MALFORMED = FIXTURES_DIR / "malformed.pdf"


@pytest.fixture(scope="module")
def clean() -> ParsedDocument:
    return parse_document(CLEAN, document_id="test-clean", persist_source=False)


@pytest.fixture(scope="module")
def multipage() -> ParsedDocument:
    return parse_document(MULTIPAGE, document_id="test-multipage", persist_source=False)


# ── Fixtures exist ───────────────────────────────────────────────────────────


def test_fixtures_present() -> None:
    """Fixtures are generated by scripts/make_fixtures.py, not committed as binaries."""
    missing = [p.name for p in (CLEAN, UNBALANCED, MULTIPAGE, SCANNED, MALFORMED) if not p.exists()]
    assert not missing, f"Run scripts/make_fixtures.py first — missing: {missing}"


# ── Table fidelity: the reason we chose Docling ──────────────────────────────


def test_clean_invoice_recovers_all_line_item_rows(clean: ParsedDocument) -> None:
    """A 3-row invoice table must yield 3 discrete rows, not one flattened string."""
    assert len(clean.tables) == 1, f"Expected 1 table, got {len(clean.tables)}"
    assert clean.tables[0].row_count == 3


def test_clean_invoice_table_has_expected_columns(clean: ParsedDocument) -> None:
    headers = {h.lower() for h in clean.tables[0].headers}
    for expected in ("description", "qty", "unit price", "amount"):
        assert expected in headers, f"Missing column {expected!r} in {headers}"


def test_clean_invoice_amounts_land_in_the_amount_column(clean: ParsedDocument) -> None:
    """Column alignment survives extraction — a misaligned table is silently wrong data."""
    amounts = {row["Amount"] for row in clean.tables[0].rows}
    assert amounts == {"30.66", "412.90", "18.44"}


def test_clean_invoice_row_values_stay_together(clean: ParsedDocument) -> None:
    """The NAT Gateway row keeps its own amount — the split-row failure mode (D-7)."""
    nat = [r for r in clean.tables[0].rows if "NAT Gateway" in r["Description"]]
    assert len(nat) == 1
    assert nat[0]["Amount"] == "412.90"
    assert nat[0]["Qty"] == "1"


def test_serialized_rows_carry_column_names(clean: ParsedDocument) -> None:
    """Phase 3 embeds these strings; column names are what make retrieval match."""
    serialized = clean.tables[0].to_serialized_rows()
    assert len(serialized) == 3
    assert any("Amount: 412.90" in row and "Description: NAT Gateway" in row for row in serialized)


# ── Provenance: citation highlighting (ODQ-1 / D-16) ─────────────────────────


def test_tables_carry_a_normalized_bbox(clean: ParsedDocument) -> None:
    bbox = clean.tables[0].bbox
    assert bbox is not None, "No bbox — citation highlighting would fall back to page level"
    assert 0.0 <= bbox.left < bbox.right <= 1.0
    assert 0.0 <= bbox.top < bbox.bottom <= 1.0


def test_bbox_converts_to_css_percentages(clean: ParsedDocument) -> None:
    css = clean.tables[0].bbox.as_css_percent()  # type: ignore[union-attr]
    assert set(css) == {"left", "top", "width", "height"}
    assert all(value.endswith("%") for value in css.values())


def test_bbox_is_top_left_origin(clean: ParsedDocument) -> None:
    """The table sits in the upper-middle of the invoice, not the bottom.

    If the bottom-left -> top-left flip were missing, this box would appear near the
    bottom of the page and every highlight in the UI would be mirrored.
    """
    bbox = clean.tables[0].bbox
    assert bbox is not None
    assert bbox.top < 0.6, f"Table bbox top={bbox.top:.3f} — coordinate flip looks wrong"


# ── Page images for the previewer ────────────────────────────────────────────


def test_page_images_are_written(clean: ParsedDocument) -> None:
    from pathlib import Path

    assert clean.pages[0].image_path is not None
    assert Path(clean.pages[0].image_path).exists()


def test_page_dimensions_are_recorded(clean: ParsedDocument) -> None:
    page = clean.pages[0]
    assert page.width_points > 0 and page.height_points > 0


# ── Multi-page handling ──────────────────────────────────────────────────────


def test_multipage_statement_has_two_pages(multipage: ParsedDocument) -> None:
    assert multipage.page_count == 2
    assert len(multipage.pages) == 2


def test_multipage_tables_are_attributed_to_the_right_pages(multipage: ParsedDocument) -> None:
    pages_with_tables = {table.page_number for table in multipage.tables}
    assert pages_with_tables == {1, 2}, f"Tables found on pages {pages_with_tables}"


def test_tables_on_page_filters_correctly(multipage: ParsedDocument) -> None:
    assert all(t.page_number == 2 for t in multipage.tables_on_page(2))


# ── Scanned input is rejected, not OCR'd (revises D-15) ──────────────────────


def test_digital_pdfs_are_not_marked_as_ocr(clean: ParsedDocument) -> None:
    """``used_ocr`` survives as a schema field but is now always False."""
    assert clean.used_ocr is False
    assert not clean.pages_needing_ocr(get_settings().text_yield_threshold)


def test_an_image_upload_is_rejected_with_an_actionable_message() -> None:
    """The OCR path is gone, so a photographed receipt cannot be read at all.

    The message has to say so. "Supported formats: .pdf" does not tell someone who just
    uploaded a photo of a receipt what to do instead, and this is a capability the
    product previously had.
    """
    with pytest.raises(ParsingError) as excinfo:
        parse_document(SCANNED, document_id="test-scanned", persist_source=False)
    message = str(excinfo.value).lower()
    assert "image" in message
    assert "pdf" in message


def test_force_ocr_is_accepted_and_ignored() -> None:
    """Kept in the signature so existing callers do not break on an unexpected keyword."""
    parsed = parse_document(CLEAN, document_id="test-forceocr", force_ocr=True, persist_source=False)
    assert parsed.used_ocr is False


# ── Error handling: specific and actionable (Rule 2.3) ───────────────────────


def test_malformed_pdf_raises_parsing_error() -> None:
    with pytest.raises(ParsingError) as excinfo:
        parse_document(MALFORMED, persist_source=False)
    message = str(excinfo.value)
    assert "malformed.pdf" in message
    assert "corrupt" in message.lower() or "not a valid" in message.lower()


def test_missing_file_raises_parsing_error() -> None:
    with pytest.raises(ParsingError, match="not found"):
        parse_document(FIXTURES_DIR / "does_not_exist.pdf", persist_source=False)


def test_unsupported_extension_lists_what_is_supported(tmp_path) -> None:  # type: ignore[no-untyped-def]
    bad = tmp_path / "notes.docx"
    bad.write_bytes(b"irrelevant")
    with pytest.raises(ParsingError) as excinfo:
        parse_document(bad, persist_source=False)
    assert ".pdf" in str(excinfo.value)


def test_empty_file_is_rejected(tmp_path) -> None:  # type: ignore[no-untyped-def]
    empty = tmp_path / "empty.pdf"
    empty.write_bytes(b"")
    with pytest.raises(ParsingError, match="empty"):
        parse_document(empty, persist_source=False)


def test_error_messages_contain_no_stack_traces() -> None:
    """Messages go straight to the UI, so they must read as English, not Python."""
    with pytest.raises(ParsingError) as excinfo:
        parse_document(MALFORMED, persist_source=False)
    message = str(excinfo.value)
    for leak in ("Traceback", "NoneType", "Exception:", "  File \""):
        assert leak not in message


# ── Fast-path triage and result caching (performance work) ───────────────────


def test_triage_detects_a_text_layer() -> None:
    """Digital PDFs must be recognised without invoking Docling."""
    from src.parser import has_text_layer

    for fixture in (CLEAN, UNBALANCED, MULTIPAGE):
        has_text, pages, chars = has_text_layer(fixture)
        assert has_text, f"{fixture.name} should report a text layer"
        assert pages >= 1 and chars > 0


def test_triage_detects_a_scanned_image() -> None:
    from src.parser import has_text_layer

    has_text, _, chars = has_text_layer(SCANNED)
    assert not has_text
    assert chars == 0


def test_triage_threshold_separates_the_real_cases() -> None:
    """A sparse multi-page statement must not be mistaken for a scan.

    The threshold answers "is there a text layer at all", not "is this page dense".
    Measured: scanned 0 chars/page, statement 289, invoice 511.
    """
    from src.config import MIN_CHARS_PER_PAGE_FOR_TEXT_LAYER
    from src.parser import has_text_layer

    _, pages, chars = has_text_layer(MULTIPAGE)
    assert chars / pages > MIN_CHARS_PER_PAGE_FOR_TEXT_LAYER


def test_triage_never_raises_on_a_corrupt_file() -> None:
    """Triage is an optimisation; it must never be what fails a parse.

    PyMuPDF opens this truncated file (the %PDF header is intact) and reports no pages,
    so triage reports no text layer. Either answer is acceptable — what matters is that
    it returns rather than raising, and that Docling still produces the actionable error.
    """
    from src.parser import has_text_layer

    has_text, pages, chars = has_text_layer(MALFORMED)
    assert isinstance(has_text, bool)
    assert chars == 0

    with pytest.raises(ParsingError):
        parse_document(MALFORMED, persist_source=False)


def test_triage_on_unreadable_bytes_defers_to_docling(tmp_path) -> None:  # type: ignore[no-untyped-def]
    """When PyMuPDF cannot open the file at all, the decision is handed to Docling."""
    from src.parser import has_text_layer

    junk = tmp_path / "junk.pdf"
    junk.write_bytes(b"this is not a pdf at all")
    has_text, _, _ = has_text_layer(junk)
    assert has_text is True  # unknown -> let Docling decide and raise properly


def test_reparsing_the_same_file_hits_the_cache() -> None:
    from src.parser import clear_parse_cache, parse_cache_info

    clear_parse_cache()
    parse_document(CLEAN, document_id="cache-1", persist_source=False)
    assert parse_cache_info()["entries"] == 1

    started = time.perf_counter()
    again = parse_document(CLEAN, document_id="cache-2", persist_source=False)
    elapsed = time.perf_counter() - started

    assert elapsed < 1.0, f"cache hit took {elapsed:.2f}s"
    assert again.document_id == "cache-2", "the caller's document_id must be honoured"


def test_cached_parse_returns_equivalent_content() -> None:
    """A cache hit must not be a degraded result."""
    from src.parser import clear_parse_cache

    clear_parse_cache()
    first = parse_document(CLEAN, document_id="eq-1", persist_source=False)
    second = parse_document(CLEAN, document_id="eq-2", persist_source=False)

    assert second.page_count == first.page_count
    assert len(second.tables) == len(first.tables)
    assert second.tables[0].rows == first.tables[0].rows
    assert second.markdown == first.markdown


def test_cache_is_keyed_on_content_not_filename(tmp_path) -> None:  # type: ignore[no-untyped-def]
    """The same bytes under a different name is still a hit."""
    from src.parser import clear_parse_cache, parse_cache_info

    clear_parse_cache()
    parse_document(CLEAN, document_id="name-1", persist_source=False)
    copy = tmp_path / "renamed.pdf"
    copy.write_bytes(CLEAN.read_bytes())
    parse_document(copy, document_id="name-2", persist_source=False)
    assert parse_cache_info()["entries"] == 1


def test_cache_reports_zero_parse_seconds_on_a_hit() -> None:
    """The Observability Bar should show a hit as free, not as a fast parse."""
    from src.parser import clear_parse_cache

    clear_parse_cache()
    parse_document(CLEAN, document_id="secs-1", persist_source=False)
    assert parse_document(CLEAN, document_id="secs-2", persist_source=False).parse_seconds == 0.0
